// Static + Worker checks for the web client. Run: node --test web/test/*.test.mjs
import { test } from 'node:test';
import { createHash } from 'node:crypto';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { existsSync } from 'node:fs';
import { PUBLIC_DIR, PROTOCOL_DIR, PROTO_FILES, I18N_DIR, HAVE_BRAND, sourceFiles, manifest, dictionaries, i18nModule, syncHtml } from '../build.mjs';
// agentjarvis/brand and agentjarvis/i18n exist in the monorepo only; the public export ships web/ alone (then the checks
// that need them are skipped, everything else still runs on the shipped copies)
const POLISH = fileURLToPath(new URL('../../i18n/polish.py', import.meta.url));
const GLOSSARY_FILE = fileURLToPath(new URL('../../i18n/glossary.json', import.meta.url));
import { handle, csp, webHeaders } from '../worker.ts';

const walk = (d) => readdirSync(d).flatMap((n) => { const p = join(d, n); return statSync(p).isDirectory() ? walk(p) : [p]; });
const files = walk(PUBLIC_DIR);
const rel = (p) => relative(PUBLIC_DIR, p).split(sep).join('/');
const read = (p) => readFileSync(p, 'utf8');
const pub = (r) => join(PUBLIC_DIR, r);
const JS = files.filter((f) => f.endsWith('.js'));
const APP = read(pub('app.js'));
// PROMPT-33: the page is app.js + the modules under js/ (relay's page ported). Every rule that used to look at app.js
// alone now looks at all of them (OURS) — the same rules over more code, never fewer.
const MODULES = ['api', 'blobs', 'boot', 'controls', 'md', 'push', 'relay', 'session', 'settings', 'snap', 'speak', 'store', 't', 'ui', 'wav', 'elevate', 'outbox', 'render', 'friends', 'qr', 'share', 'device-label'];
const OURS_FILES = ['app.js', ...MODULES.map((m) => `js/${m}.js`)];
const OURS = OURS_FILES.map((r) => read(pub(r))).join('\n');
const HTML = read(pub('index.html'));

test('expected files ship, robots.txt disallows all', () => {
  for (const r of ['index.html', 'app.js', 'app.css', 'i18n.js', 'sw.js', 'manifest.webmanifest', 'proto/noise.js', 'proto/wire.js', 'version.json', 'version.js',
    'robots.txt', 'favicon.ico', 'apple-touch-icon.png', 'brand/palette.css', 'brand/base.css', 'brand/lang.js', 'brand/ui.js', 'brand/img/icon-192.png',
    'brand/img/icon-512.png', 'brand/img/icon-512-maskable.png', 'brand/img/logo-mark.png', 'brand/img/status/logo-working.png',
    'brand/img/status/logo-waiting.png', 'brand/img/status/logo-question.png', 'brand/img/status/logo-offline.png',
    ...OURS_FILES, 'assets/rocket-mask-128.png', 'assets/rocket-mask-256.png', 'assets/rocket-lotion.png', 'assets/rocket-whoosh.mp3']) {
    assert.ok(files.includes(pub(r)), `missing public/${r}`);
  }
  assert.equal(read(pub('robots.txt')), 'User-agent: *\nDisallow: /\n');
});

test('proto/ copies are byte-identical to protocol/', () => {
  for (const n of PROTO_FILES) assert.ok(readFileSync(pub(`proto/${n}`)).equals(readFileSync(join(PROTOCOL_DIR, n))), `proto/${n} differs — run build.mjs`);
});

test('version.json / version.js match the shipped files', () => {
  const m = JSON.parse(read(pub('version.json')));
  assert.deepEqual(m, manifest(sourceFiles()), 'version.json is stale — run build.mjs');
  const shipped = files.map(rel).filter((r) => r !== 'version.json' && r !== 'version.js').sort();
  assert.deepEqual(Object.keys(m.files).sort(), shipped, 'manifest must cover every shipped file');
  assert.match(m.combined, /^[0-9a-f]{64}$/);
  assert.equal(read(pub('version.js')), `// generated by build.mjs — do not edit\nexport default ${JSON.stringify(m, null, 2)};\n`);
});

// The only absolute URLs anywhere: plain links to our own site's pages (navigation, never a resource the page loads —
// CSP default-src 'self' + connect-src = the relays enforce that too), plus — in app.js only — the new web origin the
// legacy host sends an unpaired visitor to. The relay URLs live only in the Worker CSP config (app.js pins relay HOSTS).
// (F1: the menu's 「邀请与积分」 opens the account page at its invite block — the one link with a fragment)
const SITE_LINK = /^https:\/\/agentj\.app\/(?:[a-z]+\/)*(?:#invite)?$/;
const MAIL_LINK = /^mailto:founder@agentj\.app$/;   // F13: Settings → 帮助和反馈 (the one address the site footer shows too)
const NEW_WEB_ORIGIN = 'https://m.agentj.app';
const LICENCE_TEXT = new Set(['brand/fonts/UFL-1.0-ubuntu.txt', 'brand/fonts/OFL-1.1-lexend.txt', 'brand/fonts/README.md',
  'vendor/VERSIONS.md', 'vendor/hljs/LICENSE.txt', 'vendor/katex/LICENSE.txt', 'vendor/mermaid/LICENSE.txt']);   // licence texts cite their sources
// Upstream bytes, pinned: any change must be reviewed again (P57 adds highlight.js / KaTeX / mermaid, loaded lazily by
// js/render.js; every file + its source is in vendor/VERSIONS.md, re-checked by p57_render.test.mjs).
const VENDORED = {
  'vendor/jsQR.js': 'bc40c8a15196236b2314db0856f72ca0b49980cd5413b8c852a7349f5fee0859',
  'vendor/jsQR-LICENSE.txt': 'c6596eb7be8581c18be736c846fb9173b69eccf6ef94c5135893ec56bd92ba08',
  'vendor/hljs/highlight.min.js': '8ab71eb09c51f501e5e25157d9cff100e46cc29bcbfc744d0b746d451fca7f53',
  'vendor/katex/katex.min.js': '103a53763cc033bba8d175bf3f0ba597c3505c9b6747dd3f2c7bc2a6bfcc8ae7',
  'vendor/katex/katex.min.css': 'd4ab5b8ee16989b070cdb0ea24bd6ad48fc8df1b787f280f29d3ae4f959f2c00',
  'vendor/mermaid/mermaid.min.js': '6484afc32872a3aa16cac9a76ba1816a1ed4cc870a6593cc2e17757750f518b2',
};
test('no URLs to anywhere in shipped files except links to agentj.app pages', () => {
  for (const f of files) {
    const s = read(f);
    const vendored = VENDORED;
    // License URLs in these immutable upstream bytes are attribution, not requests.
    // Any changed bytes must be reviewed again; the live browser gate checks zero off-site traffic.
    if (vendored[rel(f)]) assert.equal(createHash('sha256').update(readFileSync(f)).digest('hex'), vendored[rel(f)]);
    if (!LICENCE_TEXT.has(rel(f)) && !vendored[rel(f)]) {
      for (const m of s.matchAll(/\b(?:https?|wss?):\/\/[^\s"'<>)`]*/gi)) {
        if (rel(f) === 'app.js' && m[0] === NEW_WEB_ORIGIN) continue;
        // 0.16 (§17.1): the friend share link is text the owner copies / shows as a QR, and the SVG namespace is a name —
        // neither is ever requested (the browser gate still checks zero off-site traffic)
        if (rel(f) === 'proto/wire.js' && m[0] === 'https://m.agentj.app/friends#add=') continue;
        // ADR-A177: a compact pairing link with an empty relay field means our relay (the page still only connects where
        // allowRelay + CSP connect-src allow)
        if (rel(f) === 'proto/wire.js' && m[0] === 'wss://relay.agentj.app') continue;
        // P82 §6: owner-clicked registration link; no automated request.
        // P109: an editable API-address default sent inside the encrypted owner config, never fetched by the browser.
        if (rel(f) === 'js/bots.js' && ['https://openrouter.ai/','https://openrouter.ai/api/v1'].includes(m[0])) continue;
        if (rel(f) === 'js/qr.js' && m[0] === 'http://www.w3.org/2000/svg') continue;
        assert.match(m[0], SITE_LINK, `${rel(f)} contains URL ${m[0]}`);
      }
    }
    assert.doesNotMatch(s, /(?:src|href)\s*=\s*"\/\//i, `${rel(f)} protocol-relative URL`);
    if (!vendored[rel(f)]) assert.doesNotMatch(s, /@import/i, `${rel(f)} @import`);   // (hljs's CSS grammar names it)
  }
  for (const m of HTML.matchAll(/<(\w+)\b[^>]*\s(src|href)="([^"]*)"/g)) {
    if (m[1] === 'a') assert.match(m[3], MAIL_LINK.test(m[3]) ? MAIL_LINK : SITE_LINK, `index.html links to ${m[3]}`);
    else assert.match(m[3], /^(data:,|[a-z][\w./-]*)$/, `index.html loads ${m[3]}`);
  }
  for (const m of HTML.matchAll(/<a\b[^>]*>/g)) assert.match(m[0], /rel="noopener"/, 'site links open with rel=noopener');
});

test('no innerHTML / eval / new Function / string timers / document.write anywhere', () => {
  for (const f of JS.concat(pub('index.html'))) {
    // brand/*.js say in their header comments that they avoid these APIs; there only the code counts
    const s = rel(f).startsWith('brand/') ? read(f).replace(/\/\*[\s\S]*?\*\//g, '') : read(f);
    // pinned upstream libraries (P57: hljs / KaTeX / mermaid) may carry innerHTML / document.write code paths the page
    // never calls (hljs.highlightElement, DOMPurify …); eval / new Function / string timers stay banned there too, and
    // CSP script-src 'self' (no 'unsafe-eval') stops them at run time anyway.
    const upstream = !!VENDORED[rel(f)];
    for (const bad of [/\binnerHTML\b/, /\bouterHTML\b/, /insertAdjacentHTML/, /\beval\s*\(/, /new\s+Function\b/, /document\.write/, /setTimeout\(\s*['"`]/, /setInterval\(\s*['"`]/]) {
      if (upstream && /HTML|write/.test(bad.source)) continue;
      assert.doesNotMatch(s, bad, `${rel(f)} uses ${bad}`);
    }
  }
});

test('index.html: CSP-compatible (no inline script/style, no on*=), noindex, zh-CN, ids the e2e test drives', () => {
  assert.doesNotMatch(HTML, /<script(?![^>]*\ssrc=)[^>]*>/i);
  assert.doesNotMatch(HTML, /<style[\s>]/i);
  assert.doesNotMatch(HTML, /<[a-z][^>]*\s(style|on[a-z]+)\s*=/i);
  assert.match(HTML, /<meta name="robots" content="noindex,nofollow">/);
  assert.match(HTML, /<html lang="zh-CN">/);
  assert.match(HTML, /data-i18n="badge.label"[^>]*>网页版</);
  assert.match(HTML, /<script src="brand\/lang\.js"><\/script>/, 'lang.js runs synchronously in <head> (sets <html lang> before paint)');
  assert.match(HTML, /以后的手机 App/);                          // A2 review M-4: nothing promised in the present tense (PROMPT-29 wording)
  assert.doesNotMatch(HTML, /在公开源码上运行[^<]*结果应与上面一致/);   // the source is not public yet
  assert.match(APP, /parseLink\(input, undefined, allowRelay\)/); // A2 review L-2: the relay is pinned
  // PROMPT-33: the chat ids are relay's (the old #messages / #msg-input list is gone by design — the deck replaced it)
  for (const id of ['status', 'pair-link', 'pair-go', 'scan', 'sas', 'send', 'badge', 'badge-panel', 'version-hash', 'repair', 'retry',
    'input', 'deck', 'om', 'rm', 'words', 'rmbar', 'sheet', 'pendTag', 'tray', 'mic', 'menu', 'sug', 'keys', 'rd', 'qbar', 'meta', 'water',
    'mWeek', 'm5h', 'brand-name', 'aj-menu', 'estop-banner', 'grant-bar', 'push-row', 'confirm', 'unpair', 'mem-view', 'act-view', 'tasks-view',
    'setBtn', 'settings', 'keysBtn', 'set-font-plus', 'set-refresh', 'set-a2hs', 'set-risk-cmd', 'set-mode-cmd', 'set-iso-cmd', 'set-docker-cmd']) {
    assert.match(HTML, new RegExp(`id="${id}"`), `missing #${id}`);
  }
  const ids = [...HTML.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1]);
  assert.equal(new Set(ids).size, ids.length, 'ids are unique (relay and Agent J ids merged without a clash)');
});

const code = (s) => s.replace(/\/\*[\s\S]*?\*\//g, '').replace(/(^|[^:\\'"])\/\/.*$/gm, '$1');
test('app.js + js/*.js: only WebSocket egress, non-extractable keys, no plaintext at rest, no logging', () => {
  for (const r of OURS_FILES) {
    const raw = read(pub(r));
    // P110: exactly one browser-local SW handle request. No customer bytes, window target or network destination.
    const localClaim = "sw.postMessage({t:'share-take', id}, [ch.port2]);";
    if (r === 'js/share.js') assert.equal(raw.split(localClaim).length, 2, 'one exact local claim call');
    let s = r === 'js/share.js' ? raw.replace(localClaim, '') : raw;
    if(r === 'js/version-notice.js'){
      const exact="fetch(endpoint, {method:'GET',credentials:'omit',cache:'no-store',redirect:'error',referrerPolicy:'no-referrer',signal:AbortSignal.timeout(10000)})";
      assert.equal((s.match(/\bfetch\s*\(/g)||[]).length,1);assert.ok(s.includes(exact));
      assert.ok(s.includes("new URL('/version.json',location.origin)"));s=s.replace(exact,'VERSION_METADATA_CHECK');
    }
    if (r === 'js/store.js') {   // P122: the one export is the device key's PUBLIC half (wrapped mode, WebKit bug 312279)
      const exact = "new Uint8Array(await crypto.subtle.exportKey('raw', kp.publicKey))";
      assert.equal(s.split(exact).length, 2); s = s.replace(exact, 'PUBLIC_KEY_EXPORT');
    }
    if (r === 'js/renew.js') {   // P122: exactly one same-origin JSON POST to /.aj/rt (the ticket cookie), nothing else
      const exact = "fetch(new URL(ENDPOINT, location.origin), { method: 'POST', credentials: 'same-origin', cache: 'no-store', redirect: 'error',";
      assert.equal((s.match(/\bfetch\s*\(/g) || []).length, 1); assert.ok(s.includes(exact)); assert.match(s, /const ENDPOINT = '\/\.aj\/rt';/);
      s = s.replace(exact, 'TICKET_COOKIE_CALL');
    }
    for (const bad of [/\bfetch\s*\(/, /XMLHttpRequest/, /sendBeacon/, /\bEventSource\b/, /sessionStorage/, /\bconsole\./, /exportKey/, /document\.cookie/, /postMessage/,
      /\bnew Worker\b/, /importScripts/, /\bimport\s*\(/]) {
      assert.doesNotMatch(s, bad, `${r} uses ${bad}`);
    }
  }
  // localStorage: the "Add to Home Screen hint dismissed" flag + two display preferences (reader type size, the launch
  // colour of an iPhone home-screen app); brand/lang.js keeps the language + theme. Never chat text, drafts or history.
  const ls = OURS_FILES.flatMap((r) => [...code(read(pub(r))).matchAll(/localStorage\.(\w+)\(([^,)]*)/g)].map((m) => `${m[1]}(${m[2]})`));
  // F13: + the reply text size from Settings (FONT_KEY = "aj.fontScale", a number 0.8 … 1.6).
  // 0.15.1 (P55): + the install id (IID_KEY = "aj.iid", 16 random bytes, b64url) and the paired marker (PAIRED_KEY =
  // "aj.paired", a unix time) — no key, no channel, nothing about the computer.
  assert.deepEqual(ls.sort(), ['getItem("aj.chrome")', 'getItem(A2HS_KEY)', 'getItem(RD_KEY)', 'getItem(FONT_KEY)', 'setItem("aj.chrome")', 'setItem(A2HS_KEY)', 'setItem(RD_KEY)', 'setItem(FONT_KEY)',
    'getItem(IID_KEY)', 'setItem(IID_KEY)', 'getItem(PAIRED_KEY)', 'setItem(PAIRED_KEY)', 'removeItem(PAIRED_KEY)', "getItem('aj.homeInstalled')", "setItem('aj.homeInstalled')"].sort());
  assert.equal(OURS_FILES.reduce((n, r) => n + (code(read(pub(r))).match(/localStorage/g) || []).length, 0), 15, 'localStorage appears only in these calls (homeInstalled is a boolean, never pairing data)');
  assert.match(OURS, /const IID_KEY = 'aj\.iid';/);
  assert.match(OURS, /const PAIRED_KEY = 'aj\.paired';/);
  assert.match(OURS, /const FONT_KEY = 'aj\.fontScale';/);
  assert.match(OURS, /const A2HS_KEY = 'aj\.a2hs';/);
  assert.match(OURS, /RD_KEY = "aj\.readerFs"/);
  assert.match(OURS, /generateKeypair\(false\)/);
  assert.match(APP, /history\.replaceState/);
  // the Agent's words: Markdown through md.js (DOM nodes) or plain paragraphs via textContent — never markup
  assert.match(read(pub('js/relay.js')), /RelayMD\.toDOM\(RelayMD\.parse\(tx\), document\)/);
  assert.match(read(pub('js/relay.js')), /n\.textContent = p\.trim\(\)/);
  // IndexedDB: device key + approval key + host record + the sealing key (CryptoKeys, non-extractable) in clear;
  // drafts and input history ONLY through putSealed (AES-GCM ciphertext {v, iv, ct})
  const puts = [...new Set(OURS_FILES.flatMap((r) => [...read(pub(r)).matchAll(/dbPut\('(\w+)'/g)].map((m) => m[1])))].sort();
  // 0.15.1 (P55): + 'iid', the random install id (the other copy of localStorage "aj.iid") — no text, no key material
  // P122: + 'device2', the device key wrapped under a non-extractable AES key where X25519 cannot be stored (WebKit)
  assert.deepEqual(puts, ['device', 'device2', 'host', 'iid', 'local', 'sign'], 'plain IndexedDB writes: keys + host record + install id only');
  assert.match(read(pub('js/store.js')), /unwrapKey\('pkcs8', d\.ct, d\.kek, WRAP\(d\.iv\), \{ name: 'X25519' \}, false, \['deriveBits'\]\)/, 'the wrapped device key unwraps non-extractable');
  assert.match(read(pub('js/store.js')), /generateKey\(\{ name: 'AES-GCM', length: 256 \}, false, \['wrapKey', 'unwrapKey'\]\)/, 'wrapping key not extractable');
  const sealed = [...new Set(OURS_FILES.flatMap((r) => [...read(pub(r)).matchAll(/putSealed\("(\w+)"/g)].map((m) => m[1])))].sort();
  assert.deepEqual(sealed, ['draft', 'ihist', 'outbox'], 'sealed records: draft + input history + the offline queue (0.15.2)');
  const STORE = read(pub('js/store.js'));
  assert.match(STORE, /export async function putSealed\(name, obj\) \{\n  const w = wipes;\n  const rec = await seal\(obj\);\n  if \(w === wipes\) await dbPut\(name, rec\);\n\}/, 'putSealed writes only ciphertext, and never after a wipe');
  // §10.14 / P33-X13: revoke wipes like unpair — drafts, history, the sealing key, and everything in memory
  assert.match(APP, /async function revoked\(why = 'revoked'\) \{\n  session\.closeSession\(\);\n[^}]*await forgetLocal\(\);/, 'revoked() wipes local records');   // 0.15.1: + why
  assert.match(APP, /async function forgetLocal\(\) \{\n  forgetShare\(\);\n  relay\.forgetLocal\(\);\n  friends\.forget\(\);\n  blobs\.forgetAll\(\);\n  elevate\.clear\(\);\n  secretout\.clear\(\);\n  longtask\.clear\(\);\n  logincard\.clear\(\);\n  setupcard\.clear\(\);\n  await wipeLocal\(\);\n\}/);   // F17: open sudo / secret cards go too; 0.16: the friends page's data too; F32: pickup cards (+ a shown value); 0.18: opening cards
  assert.doesNotMatch(APP, /saveDraft/, 'revocation never saves the draft');
  assert.match(STORE, /generateKey\(\{ name: 'AES-GCM', length: 256 \}, false, \['encrypt', 'decrypt'\]\)/, 'sealing key not extractable');
  assert.match(STORE, /for \(const k of \['draft', 'ihist', 'outbox', 'local'\]\)/, 'unpair / re-pair wipes drafts, history, the offline queue and the sealing key');
  assert.match(STORE, /indexedDB\.open\('agentjarvis', 1\)/, 'the IndexedDB name stays "agentjarvis" (paired phones keep their keys)');
  assert.match(OURS, /generateSigningKeypair\(\)/);
  const WIRE = readFileSync(new URL('../../protocol/wire.js', import.meta.url), 'utf8');
  assert.match(WIRE, /generateKey\(\{ name: 'Ed25519' \}, false, \['sign', 'verify'\]\)/, 'approval key: private half not extractable');
  assert.match(OURS, /from '\.\.\/proto\/noise\.js'/);
  assert.match(OURS, /from '\.\/proto\/wire\.js'/);
  // signed decisions: approvals, question answers and control writes are Ed25519-signed with the device key
  const API = read(pub('js/api.js'));
  assert.match(API, /approveMessage\(channel\(\), await myDeviceId\(\), p\.id, decision, p\.tool, p\.summary/);
  assert.match(API, /questionMessage\(channel\(\), await myDeviceId\(\), q\.id, clean \? 'answer' : 'cancel', q\.raw, clean\)/);
  assert.match(API, /crypto\.subtle\.sign\(\{ name: 'Ed25519' \}, sk\.priv, msg\)/);
  // read aloud never uses a network voice; share goes to the phone's own sheet; whoosh from our own origin
  assert.match(read(pub('js/speak.js')), /filter\(\(v\) => v\.localService === true\)/);
  assert.match(read(pub('js/relay.js')), /navigator\.share\(\{text\}\)/);
  assert.match(read(pub('js/relay.js')), /new Audio\("assets\/rocket-whoosh\.mp3"\)/);
});

// ---------------------------------------------------------------- Worker
const RELAY = 'wss://relay.agentj.app';
const LEGACY_RELAY = 'wss://alpha-relay.agentjarvis.net';
const env = () => ({ WEB_HOST: 'm.agentj.app', LEGACY_WEB_HOST: 'alpha-web.agentjarvis.net', RELAY_URL: RELAY, LEGACY_RELAY_URL: LEGACY_RELAY,
  ASSETS: { fetch: async (req) => new Response(req.method === 'HEAD' ? null : '<html>client</html>', { headers: { 'content-type': 'text/html' } }) } });
const req = (url, { method = 'GET', headers = {} } = {}) => new Request(url, { method, headers });

test('worker: public (no Access since 2026-10-02) → asset with the full header set, still noindex — on both hosts', async () => {
  for (const origin of ['https://m.agentj.app', 'https://alpha-web.agentjarvis.net']) {
    const r = await handle(req(origin + '/'), env());
    assert.equal(r.status, 200, origin);
    assert.equal(await r.text(), '<html>client</html>');
    // connect-src = exactly our two relays (the legacy one: pairing links from not-yet-updated hosts), on both hosts
    assert.equal(r.headers.get('content-security-policy'),
      "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src wss://relay.agentj.app wss://alpha-relay.agentjarvis.net " + origin + "/version.json " + origin + "/.aj/rt" + "; " +
      "media-src 'self' blob:; frame-ancestors 'none'; base-uri 'none'; form-action 'none'; object-src 'none'", origin);
    assert.equal(r.headers.get('strict-transport-security'), 'max-age=31536000', `${origin}: HSTS`);
  }
  const r = await handle(req('https://m.agentj.app/'), env());
  // PROMPT-33: hold-to-talk records in the page (getUserMedia audio) → microphone=(self); nothing else widened
  assert.equal(r.headers.get('permissions-policy'), 'camera=(self), microphone=(self), geolocation=()');
  assert.equal(r.headers.get('x-robots-tag'), 'noindex, nofollow, noarchive');
  assert.equal(r.headers.get('referrer-policy'), 'no-referrer');
  assert.equal(r.headers.get('x-frame-options'), 'DENY');
  assert.equal(r.headers.get('x-content-type-options'), 'nosniff');
  assert.match(r.headers.get('strict-transport-security'), /max-age=\d+/);
  assert.equal(r.headers.get('cache-control'), 'private, no-store, no-transform');
  assert.equal((await handle(req('https://m.agentj.app/app.js', { method: 'HEAD' }), env())).status, 200);
  // a stale / forged Access header changes nothing
  assert.equal((await handle(req('https://m.agentj.app/', { headers: { 'cf-access-jwt-assertion': 'a.b.c' } }), env())).status, 200);
});

test('worker: wrong host, non-GET/HEAD, malformed RELAY_URL → bare 404 without the asset', async () => {
  const cases = [
    req('https://agentj.app/'),
    req('https://agentjarvis-web.example.workers.dev/'),
    req('https://web.agentj.app/'),
    req('https://alpha-web.agentj.app/'),
    req('https://agentjarvis.net/'),
    req('https://m.agentj.app.evil.example/'),
    req('https://alpha-web.agentjarvis.net/', { method: 'POST' }),
    req('https://m.agentj.app/', { method: 'POST' }),
    req('https://m.agentj.app/', { method: 'PUT' }),
    req('https://m.agentj.app/', { method: 'DELETE' }),
  ];
  for (const r of cases) {
    const res = await handle(r, env());
    assert.equal(res.status, 404, `${r.method} ${r.url}`);
    assert.equal(await res.text(), 'Not Found');
  }
  for (const RELAY_URL of ["wss://x; script-src 'unsafe-inline'", 'ws://relay.agentj.app', '']) {
    assert.equal((await handle(req('https://m.agentj.app/'), { ...env(), RELAY_URL })).status, 404, `malformed RELAY_URL ${RELAY_URL} fails closed`);
  }
  for (const LEGACY_RELAY_URL of ["wss://x; script-src 'unsafe-inline'", 'ws://alpha-relay.agentjarvis.net', 'wss://a wss://b']) {
    assert.equal((await handle(req('https://m.agentj.app/'), { ...env(), LEGACY_RELAY_URL })).status, 404, `malformed LEGACY_RELAY_URL ${LEGACY_RELAY_URL} fails closed`);
  }
  // without the legacy vars: only the new host, only the new relay
  const bare = { ...env(), LEGACY_WEB_HOST: undefined, LEGACY_RELAY_URL: undefined };
  assert.equal((await handle(req('https://alpha-web.agentjarvis.net/'), bare)).status, 404);
  assert.match((await handle(req('https://m.agentj.app/'), bare)).headers.get('content-security-policy'), /connect-src wss:\/\/relay\.agentj\.app https:\/\/m\.agentj\.app\/version\.json https:\/\/m\.agentj\.app\/\.aj\/rt; /);
  assert.equal((await handle(req('https://m.agentj.app/'), { ...env(), WEB_HOST: '' })).status, 404, 'no WEB_HOST → nothing');
});

test('worker: self-contained (no imports, so it builds from the public tree); csp()/webHeaders() are what serve.mjs reuses; wrangler.toml pins the brief', () => {
  const W = read(join(PUBLIC_DIR, '..', 'worker.ts'));
  assert.doesNotMatch(W, /^\s*import\b/m, 'worker.ts must not import anything');
  assert.doesNotMatch(W, /cf-access|Access JWT|verifyAccess/i, 'no Access check left');
  assert.match(csp('ws://127.0.0.1:*'), /connect-src ws:\/\/127\.0\.0\.1:\*;/);
  assert.equal(Object.keys(webHeaders(RELAY)).length, 8);
  const t = read(join(PUBLIC_DIR, '..', 'wrangler.toml'));
  for (const line of ['name = "agentjarvis-web"', 'main = "worker.ts"', 'compatibility_date = "2026-09-01"',
    'workers_dev = false', 'preview_urls = false', 'pattern = "m.agentj.app", custom_domain = true', 'directory = "public"', 'binding = "ASSETS"',
    'run_worker_first = true', 'WEB_HOST = "m.agentj.app"', 'RELAY_URL = "wss://relay.agentj.app"',
    'LEGACY_WEB_HOST = "alpha-web.agentjarvis.net"', 'LEGACY_RELAY_URL = "wss://alpha-relay.agentjarvis.net"']) {
    assert.ok(t.includes(line), `wrangler.toml missing: ${line}`);
  }
  assert.deepEqual([...t.matchAll(/pattern = "([^"]+)", custom_domain = true/g)].map((m) => m[1]), ['m.agentj.app', 'alpha-web.agentjarvis.net']);
  assert.match(t, /\[observability\]\nenabled = false/);
  assert.doesNotMatch(t, /ACCESS_/, 'no Access vars');
  const acct = t.match(/^account_id = "(.*)"$/m);
  if (acct) assert.match(acct[1], /^[0-9a-f]{32}$/);   // the public copy has no account_id (set your own)
});

// ---------------------------------------------------------------- L1: service worker + manifest (PROTOCOL §9)
test('sw.js: local share intake + generic push — no cache, no network, no persistent content', () => {
  const SW = readFileSync(join(PUBLIC_DIR, 'sw.js'), 'utf8');
  for (const bad of [/\bcaches\b/, /\bfetch\s*\(/, /importScripts/, /XMLHttpRequest/, /\bconsole\./, /indexedDB/]) {
    assert.doesNotMatch(SW, bad, `sw.js uses ${bad}`);
  }
  assert.match(SW, /zh: \{ reply: '有新回复', ask: '有一个请求等你批准', security: 'Agent J 有紧急安全更新' \}/);
  assert.match(SW, /en: \{ reply: 'New reply', ask: 'A request is waiting for your approval', security: 'Agent J has an urgent security update' \}/);
  assert.match(SW, /showNotification\('Agent J', \{ body: BODY\[LANG\]\[k\]/, 'the notification body is one of the three fixed sentences');
  assert.match(SW, /const SW_VERSION = 'aj-web-[\w-]+';/, 'sw.js carries a version string (bumped with each shell redesign)');
  assert.match(OURS, /userVisibleOnly: true/);
  assert.match(OURS, /serviceWorker\.register\('sw\.js'/);
});

test('manifest + icons are local files from the brand (192, 512, 512 maskable), colours from tokens', () => {
  const m = JSON.parse(readFileSync(join(PUBLIC_DIR, 'manifest.webmanifest'), 'utf8'));
  assert.equal(m.display, 'standalone');
  assert.equal(m.name, 'Agent J');
  assert.ok(m.short_name && m.short_name.length <= 12);
  for (const i of m.icons) assert.ok(!/^[a-z]+:/i.test(i.src) && i.src.startsWith('brand/img/') && statSync(join(PUBLIC_DIR, i.src)).size > 0, i.src);
  assert.deepEqual(m.icons.map((i) => `${i.sizes}/${i.purpose}`), ['192x192/any', '512x512/any', '512x512/maskable']);
  const TOK = read(pub('brand/palette.css'));
  for (const c of [m.background_color, m.theme_color]) assert.ok(TOK.includes(`: ${c};`), `${c} is a brand token`);
  assert.match(HTML, /<meta name="theme-color" content="#faf9f5" media="\(prefers-color-scheme: light\)">/);
  assert.match(HTML, /<meta name="theme-color" content="#141414" media="\(prefers-color-scheme: dark\)">/);
  assert.match(HTML, /<link rel="apple-touch-icon" href="apple-touch-icon\.png">/);
  assert.match(HTML, /<link rel="manifest" href="manifest\.webmanifest">/);
});

// ---------------------------------------------------------------- brand + i18n
test('brand copy is current (brand/sync.mjs --set web --check)', { skip: !HAVE_BRAND && 'no agentjarvis/brand (public export)' }, () => {
  const r = spawnSync(process.execPath, [fileURLToPath(new URL('../../brand/sync.mjs', import.meta.url)), PUBLIC_DIR, '--set', 'web', '--check'], { encoding: 'utf8' });
  assert.equal(r.status, 0, r.stdout + r.stderr);
});

const DICT = dictionaries();
const ph = (s) => (s.match(/\{\w+\}/g) || []).sort().join(' ');
test('i18n: zh and en have the same keys and placeholders; i18n.js and index.html are built from them', () => {
  assert.deepEqual(Object.keys(DICT.en).sort(), Object.keys(DICT.zh).sort());
  for (const k of Object.keys(DICT.zh)) {
    assert.equal(ph(DICT.en[k]), ph(DICT.zh[k]), `placeholders differ for ${k}`);
    assert.ok(DICT.zh[k].trim() && DICT.en[k].trim(), `empty string for ${k}`);
    assert.equal((DICT.zh[k].match(/`/g) || []).length % 2, 0, `unbalanced backticks zh ${k}`);
    assert.equal((DICT.en[k].match(/`/g) || []).length % 2, 0, `unbalanced backticks en ${k}`);
  }
  assert.equal(read(pub('i18n.js')), i18nModule(DICT), 'public/i18n.js is stale — run build.mjs');
  assert.equal(HTML, syncHtml(HTML, DICT.zh), 'index.html Chinese text differs from web.zh.json — run build.mjs');
  for (const m of HTML.matchAll(/data-i18n="([\w.]+)"/g)) assert.ok(DICT.zh[m[1]], `index.html: unknown key ${m[1]}`);
  for (const m of OURS.matchAll(/\bt\('([\w.]+)'/g)) {
    if (m[1].endsWith('.')) assert.ok(Object.keys(DICT.zh).some((k) => k.startsWith(m[1])), `app.js: no keys under ${m[1]}`);
    else assert.ok(DICT.zh[m[1]], `app.js: unknown key ${m[1]}`);
  }
});

test('i18n: the Chinese is the polished output (i18n/polish.py --check, offline)', { skip: !existsSync(POLISH) && 'no agentjarvis/i18n (public export)' }, () => {
  // 0.15 (P44): the web dictionary is polished with qwen/qwen3.6-flash (the release brief's model), so the check uses it too
  const r = spawnSync('python3', [POLISH, '--check', '--model', 'qwen/qwen3.6-flash', I18N_DIR], { encoding: 'utf8' });
  assert.equal(r.status, 0, r.stdout + r.stderr);
});

// glossary.json "forbidden" patterns are Python regexes: a leading (?i) becomes the JS i flag; (?i:…) groups are native
const GLOSSARY = existsSync(GLOSSARY_FILE) ? JSON.parse(read(GLOSSARY_FILE)) : null;
const NO_GLOSSARY = !GLOSSARY && 'no agentjarvis/i18n (public export)';
const jsRe = (p) => (p.startsWith('(?i)') ? new RegExp(p.slice(4), 'i') : new RegExp(p));
test('i18n: no internal terms or banned words in either dictionary, the page text or app.js literals', { skip: NO_GLOSSARY }, () => {
  const visible = HTML.replace(/<script[\s\S]*?<\/script>|<[^>]+>/g, ' ');
  const sources = [...Object.entries(DICT.zh).map(([k, v]) => [`zh ${k}`, v]), ...Object.entries(DICT.en).map(([k, v]) => [`en ${k}`, v]), ['index.html text', visible]];
  for (const f of GLOSSARY.forbidden) {
    const re = jsRe(f.pattern);
    for (const [where, text] of sources) assert.doesNotMatch(text, re, `${where}: internal term /${f.pattern}/ — say 「${f.say_zh}」 / "${f.say_en}"`);
  }
  for (const [k, v] of Object.entries(DICT.zh)) {
    for (const w of GLOSSARY.banned_words_zh) assert.ok(!v.includes(w), `zh ${k}: banned word ${w}`);
    for (const p of GLOSSARY.banned_patterns_zh) assert.doesNotMatch(v, new RegExp(p), `zh ${k}: banned pattern ${p}`);
  }
  // every user-visible Chinese string lives in the dictionary: app.js code has no Chinese except the device label sent to
  // the host ("网页 · Chrome" is data for the computer's device list; 0.15.1: "网页 · iOS 主屏幕" for the Home Screen app) and comments
  const appCode = (APP + read(pub('js/device-label.js'))).replace(/\/\/.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '');
  const cjk = [...new Set(appCode.match(/[㐀-鿿]+/g) || [])];
  assert.ok(cjk.includes('网页') && cjk.every((w) => ['浏览器', '网页', '主屏幕', '华为手机', '华为平板'].includes(w)), `app.js has UI Chinese outside the dictionary: ${cjk.join(' ')}`);
  for (const r of OURS_FILES.filter((x) => x !== 'app.js' && x !== 'js/device-label.js')) {             // the modules: no Chinese in code at all
    const c = read(pub(r)).replace(/\/\/.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '');
    assert.deepEqual(c.match(/[㐀-鿿]+/g) || [], [], `${r} has UI Chinese outside the dictionary`);
  }
  // relay was Leo's private tool: no owner name, private bot or assistant name may reach the product's words (PROMPT-33)
  for (const [where, text] of sources) assert.doesNotMatch(text, /\bLeo\b|Telegram|贾维斯|\bJarvis\b|J\.A\.R\.V\.I\.S/i, `${where}: relay's private wording`);
});

test('i18n: the forbidden-term check itself works (positive control)', { skip: NO_GLOSSARY }, () => {
  const planted = ['Noise 握手', '急停', 'alpha', 'harness', 'Zero Access'];
  for (const s of planted) assert.ok(GLOSSARY.forbidden.some((f) => jsRe(f.pattern).test(s)), `no forbidden pattern catches ${s}`);
});


// ---------------------------------------------------------------- rename (agentj.app): relay pinning, legacy host, Agent name
test('app.js pins exactly our two relay hosts; the legacy host sends a visitor with no pairing to m.agentj.app, hash intact', () => {
  assert.match(APP, /const RELAY_HOSTS = \['relay\.agentj\.app', 'alpha-relay\.agentjarvis\.net'\];/);
  assert.match(APP, /const ours = u\.protocol === 'wss:' && !u\.port && RELAY_HOSTS\.includes\(u\.hostname\);/);
  assert.match(APP, /const LEGACY_WEB_HOST = 'alpha-web\.agentjarvis\.net';/);
  assert.match(APP, /const WEB_ORIGIN = 'https:\/\/m\.agentj\.app';/);
  assert.match(APP, /location\.replace\(WEB_ORIGIN \+ location\.pathname \+ location\.search \+ \(pendingLink \?\? location\.hash\)\)/);
  assert.match(APP, /async function main\(\) \{\n  if \(await leaveLegacyHost\(\)\) return;/, 'the legacy check runs first (before any key is made there)');
  assert.doesNotMatch(APP, /startsWith\('alpha-relay\.'\)|replace\(\/\^alpha-web/, 'no relay derived from the page host any more');
});

// cleanName() lifted out of app.js and run here on hostile input (the screens test drives the same through the page)
const CLEAN_SRC = APP.match(/const NAME_MAX = \d+;[\s\S]*?\nfunction cleanName\(v\) \{[\s\S]*?\n\}/)[0];
const cleanName = new Function(`${CLEAN_SRC}; return cleanName;`)();
test('F1: the menu offers 「邀请与积分」, a plain new-tab link to the account page\'s invite block (no script, no token in the URL)', () => {
  const a = HTML.match(/<a [^>]*data-i18n="menu\.invite"[^>]*>([^<]*)<\/a>/);
  assert.ok(a, 'menu invite entry present');
  const tag = a[0];
  assert.match(tag, /\bhref="https:\/\/agentj\.app\/account\/#invite"/);
  assert.match(tag, /\btarget="_blank"/);
  assert.match(tag, /\brel="noopener"/);
  assert.match(tag, /class="ajmenu__item"/);
  const d = dictionaries();
  assert.equal(d.zh['menu.invite'], '邀请与积分');
  assert.equal(d.en['menu.invite'], 'Invites and points');
  assert.equal(a[1], d.zh['menu.invite'], 'zh fallback text in the page = the dictionary');
  // the entry sits inside the ≡ menu, before the help links
  assert.ok(HTML.indexOf('data-i18n="menu.invite"') < HTML.indexOf('data-i18n="menu.help"'));
});
test('Agent name from the host: text only, control / format chars dropped, ≤ 32 code points, null → default', () => {
  assert.equal(cleanName('Leo 的助手'), 'Leo 的助手');
  assert.equal(cleanName('  市场部   Agent  '), '市场部 Agent');
  for (const v of [null, undefined, 42, {}, [], '', '   ', '\u200b\u202e\u0000']) assert.equal(cleanName(v), null, JSON.stringify(v));
  assert.equal(cleanName('a\u202eb\u200dc\u0007d\u2028e\ufeff'), 'abcd e');         // bidi override, ZWJ, BEL dropped; LS = a break
  assert.equal(cleanName('a\tb\nc\u3000d'), 'a b c d');
  assert.equal(cleanName('a \u0007 b'), 'a b');
  assert.equal(cleanName('\ue000x\ud800y'), 'xy');                                    // private use, lone surrogate
  const long = cleanName('名'.repeat(40));
  assert.equal(Array.from(long).length, 32);
  assert.equal(Array.from(cleanName('😀'.repeat(40))).length, 32, 'counted in code points, never splits a surrogate pair');
  assert.equal(cleanName('<img src=x onerror=alert(1)>'), '<img src=x onerror=alert(1)>', 'markup stays text (textContent renders it)');
  assert.ok(cleanName('x'.repeat(100000)).length <= 32);
  // shown via textContent only, default "Agent J"
  assert.match(APP, /\$\('brand-name'\)\.textContent = agentName \?\? DEFAULT_NAME;/);
  assert.match(APP, /const DEFAULT_NAME = 'Agent J';/);
  assert.match(APP, /case 'status': setAgentName\(m\.name\);/);
});

// G-A130 / ADR-A140 (PR1): Cloudflare Web Analytics injects its beacon <script> into HTML answered to a browser unless the
// response carries Cache-Control: no-transform — every answer of this Worker carries it (page, asset, bare 404).
test('worker: G-A130 every response carries Cache-Control no-transform (HTML page as Chrome asks, asset, 404)', async () => {
  const chrome = { accept: 'text/html,application/xhtml+xml,*/*;q=0.8', 'user-agent': 'Mozilla/5.0 Chrome/141.0.0.0' };
  for (const r of [await handle(req('https://m.agentj.app/', { headers: chrome }), env()), await handle(req('https://m.agentj.app/app.js'), env()),
    await handle(req('https://evil.example/', { headers: chrome }), env()), await handle(req('https://m.agentj.app/', { method: 'POST' }), env())]) {
    assert.match(r.headers.get('cache-control') ?? '', /(^|, )no-transform(,|$)/, `${r.status}`);
  }
  assert.match(webHeaders(RELAY)['cache-control'], /no-store, no-transform/);
});

test('F13 Settings: the gear replaced the bulb; s / ⌘, / Ctrl+, / ? wired; pref_set only for the four user keys; safety rows read-only', () => {
  const SET = read(pub('js/settings.js')), RELAY = read(pub('js/relay.js'));
  const top = HTML.slice(HTML.indexOf('<header class="top">'), HTML.indexOf('</header>'));
  assert.match(top, /id="setBtn"[^>]*aria-controls="settings"/, 'the header has the Settings gear');
  assert.doesNotMatch(top, /id="keysBtn"/, 'the lightbulb left the header');
  const panel = HTML.slice(HTML.indexOf('<section id="settings"'), HTML.indexOf('</section>', HTML.indexOf('<section id="settings"')));
  assert.match(panel, /id="keysBtn"/, 'the shortcut sheet is a second-level item in Settings');
  assert.match(HTML, /<dt><kbd>s<\/kbd> · <kbd>Ctrl<\/kbd>\+<kbd>,<\/kbd><\/dt><dd data-i18n="r\.keys\.s">/, 'the shortcut sheet lists s · Ctrl+,');
  assert.match(RELAY, /\(e\.ctrlKey \|\| e\.metaKey\) && !e\.altKey && !e\.shiftKey && \(e\.key === "," \|\| e\.code === "Comma"\)/);
  assert.match(RELAY, /if \(e\.key === "s" && !e\.shiftKey\)\{ e\.preventDefault\(\); closeMenu\(\); closeSug\(\); C\.settings && C\.settings\(\); return; \}/);
  assert.match(RELAY, /if \(e\.key === "\?"\)\{ e\.preventDefault\(\); openKeys\(\); return; \}/, '? still opens the sheet');
  assert.match(RELAY, /el\("keysBtn"\)\.addEventListener\("click", openKeys\)/);
  // C6 / Amendment A1: exactly these keys go to the host; the font size never does; nothing lowers safety from the phone
  assert.match(SET, /export const PREF_KEYS = \['appearance\.language', 'appearance\.theme', 'voice\.speak_replies', 'voice\.wake_enabled', 'agent\.high_risk_warnings', 'agent\.session_mode', 'agent\.isolation', 'agent\.allow_docker'\];/);
  assert.match(SET, /if \(!PREF_KEYS\.includes\(key\)\) return false;/);
  assert.match(SET, /ask1\(\{ t: 'pref_set', key, value \}, 'pref_res', 8000\)/);
  assert.doesNotMatch(SET, /pref_set'[^\n]*agent\./);
  assert.match(panel, /data-pref="agent\.high_risk_warnings"/, 'risk switch available');
  assert.match(panel, /data-pref="agent\.session_mode"/, 'mode switch available');
  assert.match(SET, /cmdFor\('agent\.high_risk_warnings'/);
  assert.match(SET, /cmdFor\('agent\.session_mode'/);
  // F14 (P45b): isolation and docker are the owner's switches on a paired phone
  assert.match(panel, /data-pref="agent\.isolation"/, 'isolation switch available');
  assert.match(panel, /data-pref="agent\.allow_docker"/, 'docker switch available');
  assert.match(SET, /cmdFor\('agent\.isolation'/);
  assert.match(SET, /cmdFor\('agent\.allow_docker'/);
  // update app: unregister every worker, drop Cache Storage, reload — no fetch (CSP connect-src = the relays only)
  assert.match(SET, /navigator\.serviceWorker\.getRegistrations\(\)/);
  assert.match(SET, /await r\.unregister\(\)/);
  assert.match(SET, /caches\.delete\(k\)/);
  // Add to Home Screen: the Android prompt kept for our button; the iPhone guide; hidden when standalone
  assert.match(SET, /addEventListener\('beforeinstallprompt', \(e\) => \{ e\.preventDefault\(\); installEvt = e;/);
  assert.match(SET, /if \(push\.standalone\(\)\) return 'done';/);
  assert.equal((panel.match(/<li>/g) || []).length, 3, 'three illustrated iPhone steps');
  // reply text size: 7 steps, below and above 1 (0.14 sizes sit inside the range); the reply card uses --rs
  assert.match(SET, /export const FONT_STEPS = \[0\.8, 0\.9, 1, 1\.1, 1\.25, 1\.4, 1\.6\];/);
  assert.match(read(pub('app.css')), /\.words\{font-size:calc\(18px\*var\(--fz\)\*var\(--rs\)\)/);
  // push off is the §9 message, inside the session
  assert.match(read(pub('js/push.js')), /sendApp\(\{ t: 'push_off' \}\)/);
});
