// Static + Worker checks for the web client. Run: node --test web/test/*.test.mjs
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { PUBLIC_DIR, PROTOCOL_DIR, PROTO_FILES, sourceFiles, manifest } from '../build.mjs';
import { handle, csp, webHeaders } from '../worker.ts';

const walk = (d) => readdirSync(d).flatMap((n) => { const p = join(d, n); return statSync(p).isDirectory() ? walk(p) : [p]; });
const files = walk(PUBLIC_DIR);
const rel = (p) => relative(PUBLIC_DIR, p).split(sep).join('/');
const read = (p) => readFileSync(p, 'utf8');
const pub = (r) => join(PUBLIC_DIR, r);
const JS = files.filter((f) => f.endsWith('.js'));
const APP = read(pub('app.js'));
const HTML = read(pub('index.html'));

test('expected files ship, robots.txt disallows all', () => {
  for (const r of ['index.html', 'app.js', 'app.css', 'proto/noise.js', 'proto/wire.js', 'version.json', 'version.js', 'robots.txt']) {
    assert.ok(files.includes(pub(r)), `missing public/${r}`);
  }
  assert.equal(read(pub('robots.txt')), 'User-agent: *\nDisallow: /\n');
});

test('proto/ copies are byte-identical to protocol/', () => {
  for (const n of PROTO_FILES) assert.ok(readFileSync(pub(`proto/${n}`)).equals(readFileSync(join(PROTOCOL_DIR, n))), `proto/${n} differs — run build.mjs`);
});

test('version.json / version.js match the shipped files', () => {
  const m = JSON.parse(read(pub('version.json')));
  assert.deepEqual(m, manifest(sourceFiles()), 'version.json is stale — run build.mjs');
  const shipped = files.map(rel).filter((r) => r !== 'version.json' && r !== 'version.js').sort();
  assert.deepEqual(Object.keys(m.files).sort(), shipped, 'manifest must cover every shipped file');
  assert.match(m.combined, /^[0-9a-f]{64}$/);
  assert.equal(read(pub('version.js')), `// generated by build.mjs — do not edit\nexport default ${JSON.stringify(m, null, 2)};\n`);
});

test('no URLs to anywhere in shipped files (the relay URL lives only in the Worker CSP config)', () => {
  for (const f of files) {
    const s = read(f);
    for (const m of s.matchAll(/\b(?:https?|wss?):\/\/[^\s"'<>)]*/gi)) assert.fail(`${rel(f)} contains URL ${m[0]}`);
    assert.doesNotMatch(s, /(?:src|href)\s*=\s*"\/\//i, `${rel(f)} protocol-relative URL`);
    assert.doesNotMatch(s, /@import/i, `${rel(f)} @import`);
  }
  for (const m of HTML.matchAll(/\s(?:src|href)="([^"]*)"/g)) assert.match(m[1], /^(data:,|[a-z][\w./-]*)$/, `index.html loads ${m[1]}`);
});

test('no innerHTML / eval / new Function / string timers / document.write anywhere', () => {
  for (const f of JS.concat(pub('index.html'))) {
    const s = read(f);
    for (const bad of [/\binnerHTML\b/, /\bouterHTML\b/, /insertAdjacentHTML/, /\beval\s*\(/, /new\s+Function\b/, /document\.write/, /setTimeout\(\s*['"`]/, /setInterval\(\s*['"`]/]) {
      assert.doesNotMatch(s, bad, `${rel(f)} uses ${bad}`);
    }
  }
});

test('index.html: CSP-compatible (no inline script/style, no on*=), noindex, zh-CN, ids the e2e test drives', () => {
  assert.doesNotMatch(HTML, /<script(?![^>]*\ssrc=)[^>]*>/i);
  assert.doesNotMatch(HTML, /<style[\s>]/i);
  assert.doesNotMatch(HTML, /<[a-z][^>]*\s(style|on[a-z]+)\s*=/i);
  assert.match(HTML, /<meta name="robots" content="noindex,nofollow">/);
  assert.match(HTML, /<html lang="zh-CN">/);
  assert.match(HTML, /网页版 · 改了会被发现（建设中）/);
  assert.match(HTML, /原生 App（计划中/);                       // A2 review M-4: nothing promised in the present tense
  assert.doesNotMatch(HTML, /在公开源码上运行[^<]*结果应与上面一致/);   // the source is not public yet
  assert.match(APP, /parseLink\(input, undefined, allowRelay\)/); // A2 review L-2: the relay is pinned
  for (const id of ['status', 'pair-link', 'pair-go', 'scan', 'sas', 'messages', 'msg-input', 'send', 'badge', 'badge-panel', 'version-hash', 'repair', 'retry']) {
    assert.match(HTML, new RegExp(`id="${id}"`), `missing #${id}`);
  }
});

test('app.js: only WebSocket egress, non-extractable device key, no plaintext at rest, no logging', () => {
  for (const bad of [/\bfetch\s*\(/, /XMLHttpRequest/, /sendBeacon/, /\bEventSource\b/, /localStorage/, /sessionStorage/, /\bconsole\./, /exportKey/, /document\.cookie/, /postMessage/]) {
    assert.doesNotMatch(APP, bad, `app.js uses ${bad}`);
  }
  assert.match(APP, /generateKeypair\(false\)/);
  assert.match(APP, /history\.replaceState/);
  assert.match(APP, /textContent = text/);
  assert.deepEqual([...APP.matchAll(/dbPut\('(\w+)'/g)].map((m) => m[1]).sort(), ['device', 'host', 'sign'], 'IndexedDB writes: device key + approval key + host record only');
  assert.match(APP, /generateSigningKeypair\(\)/);
  const WIRE = readFileSync(new URL('../../protocol/wire.js', import.meta.url), 'utf8');
  assert.match(WIRE, /generateKey\(\{ name: 'Ed25519' \}, false, \['sign', 'verify'\]\)/, 'approval key: private half not extractable');
  assert.match(APP, /from '\.\/proto\/noise\.js'/);
  assert.match(APP, /from '\.\/proto\/wire\.js'/);
});

// ---------------------------------------------------------------- Worker
const RELAY = 'wss://alpha-relay.agentjarvis.net';
const env = () => ({ WEB_HOST: 'alpha-web.agentjarvis.net', RELAY_URL: RELAY,
  ASSETS: { fetch: async (req) => new Response(req.method === 'HEAD' ? null : '<html>client</html>', { headers: { 'content-type': 'text/html' } }) } });
const req = (url, { method = 'GET', headers = {} } = {}) => new Request(url, { method, headers });

test('worker: public (no Access since 2026-10-02) → asset with the full header set, still noindex', async () => {
  const r = await handle(req('https://alpha-web.agentjarvis.net/'), env());
  assert.equal(r.status, 200);
  assert.equal(await r.text(), '<html>client</html>');
  assert.equal(r.headers.get('content-security-policy'),
    "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data: blob:; connect-src wss://alpha-relay.agentjarvis.net; " +
    "media-src 'self' blob:; frame-ancestors 'none'; base-uri 'none'; form-action 'none'; object-src 'none'");
  assert.equal(r.headers.get('permissions-policy'), 'camera=(self), microphone=(), geolocation=()');
  assert.equal(r.headers.get('x-robots-tag'), 'noindex, nofollow, noarchive');
  assert.equal(r.headers.get('referrer-policy'), 'no-referrer');
  assert.equal(r.headers.get('x-frame-options'), 'DENY');
  assert.equal(r.headers.get('x-content-type-options'), 'nosniff');
  assert.match(r.headers.get('strict-transport-security'), /max-age=\d+/);
  assert.equal(r.headers.get('cache-control'), 'private, no-store');
  assert.equal((await handle(req('https://alpha-web.agentjarvis.net/app.js', { method: 'HEAD' }), env())).status, 200);
  // a stale / forged Access header changes nothing
  assert.equal((await handle(req('https://alpha-web.agentjarvis.net/', { headers: { 'cf-access-jwt-assertion': 'a.b.c' } }), env())).status, 200);
});

test('worker: wrong host, non-GET/HEAD, malformed RELAY_URL → bare 404 without the asset', async () => {
  const cases = [
    req('https://alpha.agentjarvis.net/'),
    req('https://agentjarvis-web.example.workers.dev/'),
    req('https://web.agentjarvis.net/'),
    req('https://alpha-web.agentjarvis.net/', { method: 'POST' }),
    req('https://alpha-web.agentjarvis.net/', { method: 'PUT' }),
    req('https://alpha-web.agentjarvis.net/', { method: 'DELETE' }),
  ];
  for (const r of cases) {
    const res = await handle(r, env());
    assert.equal(res.status, 404, `${r.method} ${r.url}`);
    assert.equal(await res.text(), 'Not Found');
  }
  for (const RELAY_URL of ["wss://x; script-src 'unsafe-inline'", 'ws://alpha-relay.agentjarvis.net', '']) {
    assert.equal((await handle(req('https://alpha-web.agentjarvis.net/'), { ...env(), RELAY_URL })).status, 404, `malformed RELAY_URL ${RELAY_URL} fails closed`);
  }
});

test('worker: self-contained (no imports, so it builds from the public tree); csp()/webHeaders() are what serve.mjs reuses; wrangler.toml pins the brief', () => {
  const W = read(join(PUBLIC_DIR, '..', 'worker.ts'));
  assert.doesNotMatch(W, /^\s*import\b/m, 'worker.ts must not import anything');
  assert.doesNotMatch(W, /cf-access|Access JWT|verifyAccess/i, 'no Access check left');
  assert.match(csp('ws://127.0.0.1:*'), /connect-src ws:\/\/127\.0\.0\.1:\*;/);
  assert.equal(Object.keys(webHeaders(RELAY)).length, 8);
  const t = read(join(PUBLIC_DIR, '..', 'wrangler.toml'));
  for (const line of ['name = "agentjarvis-web"', 'main = "worker.ts"', 'compatibility_date = "2026-09-01"',
    'workers_dev = false', 'preview_urls = false', 'pattern = "alpha-web.agentjarvis.net", custom_domain = true', 'directory = "public"', 'binding = "ASSETS"',
    'run_worker_first = true', 'WEB_HOST = "alpha-web.agentjarvis.net"', 'RELAY_URL = "wss://alpha-relay.agentjarvis.net"']) {
    assert.ok(t.includes(line), `wrangler.toml missing: ${line}`);
  }
  assert.match(t, /\[observability\]\nenabled = false/);
  assert.doesNotMatch(t, /ACCESS_/, 'no Access vars');
  const acct = t.match(/^account_id = "(.*)"$/m);
  if (acct) assert.match(acct[1], /^[0-9a-f]{32}$/);   // the public copy has no account_id (set your own)
});

// ---------------------------------------------------------------- L1: service worker + manifest (PROTOCOL §9)
test('sw.js: push display only — no fetch handler, no cache, no network, generic text only', () => {
  const SW = readFileSync(join(PUBLIC_DIR, 'sw.js'), 'utf8');
  for (const bad of [/addEventListener\(\s*['"]fetch/, /\bcaches\b/, /\bfetch\s*\(/, /importScripts/, /XMLHttpRequest/, /\bconsole\./, /indexedDB/]) {
    assert.doesNotMatch(SW, bad, `sw.js uses ${bad}`);
  }
  assert.match(SW, /reply: '有新回复', ask: '有一个请求等你批准'/);
  assert.match(SW, /showNotification\('Agent Jarvis', \{ body: BODY\[k\]/, 'the notification body is one of the two fixed sentences');
  const APP2 = readFileSync(join(PUBLIC_DIR, 'app.js'), 'utf8');
  assert.match(APP2, /userVisibleOnly: true/);
  assert.match(APP2, /serviceWorker\.register\('sw\.js'/);
});

test('manifest + icons are local files', () => {
  const m = JSON.parse(readFileSync(join(PUBLIC_DIR, 'manifest.webmanifest'), 'utf8'));
  assert.equal(m.display, 'standalone');
  for (const i of m.icons) assert.ok(!/^[a-z]+:/i.test(i.src) && statSync(join(PUBLIC_DIR, i.src)).size > 0, i.src);
});
