// Static + Worker checks for the web client. Run: node --test web/test/*.test.mjs
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { existsSync } from 'node:fs';
import { PUBLIC_DIR, PROTOCOL_DIR, PROTO_FILES, I18N_DIR, HAVE_BRAND, sourceFiles, manifest, dictionaries, i18nModule, syncHtml } from '../build.mjs';
// agentjarvis/brand and agentjarvis/i18n exist in the monorepo only; the public export ships web/ alone (then the checks
// that need them are skipped, everything else still runs on the shipped copies)
const POLISH = fileURLToPath(new URL('../../i18n/polish.py', import.meta.url));
const GLOSSARY_FILE = fileURLToPath(new URL('../../i18n/glossary.json', import.meta.url));
import { handle, csp, webHeaders } from '../worker.ts';

const walk = (d) => readdirSync(d).flatMap((n) => { const p = join(d, n); return statSync(p).isDirectory() ? walk(p) : [p]; });
const files = walk(PUBLIC_DIR);
const rel = (p) => relative(PUBLIC_DIR, p).split(sep).join('/');
const read = (p) => readFileSync(p, 'utf8');
const pub = (r) => join(PUBLIC_DIR, r);
const JS = files.filter((f) => f.endsWith('.js'));
const APP = read(pub('app.js'));
const HTML = read(pub('index.html'));

test('expected files ship, robots.txt disallows all', () => {
  for (const r of ['index.html', 'app.js', 'app.css', 'i18n.js', 'sw.js', 'manifest.webmanifest', 'proto/noise.js', 'proto/wire.js', 'version.json', 'version.js',
    'robots.txt', 'favicon.ico', 'apple-touch-icon.png', 'brand/palette.css', 'brand/base.css', 'brand/lang.js', 'brand/ui.js', 'brand/img/icon-192.png',
    'brand/img/icon-512.png', 'brand/img/icon-512-maskable.png', 'brand/img/logo-mark.png', 'brand/img/status/logo-working.png',
    'brand/img/status/logo-waiting.png', 'brand/img/status/logo-question.png', 'brand/img/status/logo-offline.png']) {
    assert.ok(files.includes(pub(r)), `missing public/${r}`);
  }
  assert.equal(read(pub('robots.txt')), 'User-agent: *\nDisallow: /\n');
});

test('proto/ copies are byte-identical to protocol/', () => {
  for (const n of PROTO_FILES) assert.ok(readFileSync(pub(`proto/${n}`)).equals(readFileSync(join(PROTOCOL_DIR, n))), `proto/${n} differs — run build.mjs`);
});

test('version.json / version.js match the shipped files', () => {
  const m = JSON.parse(read(pub('version.json')));
  assert.deepEqual(m, manifest(sourceFiles()), 'version.json is stale — run build.mjs');
  const shipped = files.map(rel).filter((r) => r !== 'version.json' && r !== 'version.js').sort();
  assert.deepEqual(Object.keys(m.files).sort(), shipped, 'manifest must cover every shipped file');
  assert.match(m.combined, /^[0-9a-f]{64}$/);
  assert.equal(read(pub('version.js')), `// generated by build.mjs — do not edit\nexport default ${JSON.stringify(m, null, 2)};\n`);
});

// The only absolute URLs anywhere: plain links to our own site's pages (navigation, never a resource the page loads —
// CSP default-src 'self' + connect-src = the relay enforce that too). The relay URL lives only in the Worker CSP config.
const SITE_LINK = /^https:\/\/agentjarvis\.net\/(?:[a-z]+\/)*$/;
const LICENCE_TEXT = new Set(['brand/fonts/UFL-1.0-ubuntu.txt', 'brand/fonts/OFL-1.1-lexend.txt', 'brand/fonts/README.md']);   // licence texts cite their sources
test('no URLs to anywhere in shipped files except links to agentjarvis.net pages', () => {
  for (const f of files) {
    const s = read(f);
    if (!LICENCE_TEXT.has(rel(f))) {
      for (const m of s.matchAll(/\b(?:https?|wss?):\/\/[^\s"'<>)`]*/gi)) assert.match(m[0], SITE_LINK, `${rel(f)} contains URL ${m[0]}`);
    }
    assert.doesNotMatch(s, /(?:src|href)\s*=\s*"\/\//i, `${rel(f)} protocol-relative URL`);
    assert.doesNotMatch(s, /@import/i, `${rel(f)} @import`);
  }
  for (const m of HTML.matchAll(/<(\w+)\b[^>]*\s(src|href)="([^"]*)"/g)) {
    if (m[1] === 'a') assert.match(m[3], SITE_LINK, `index.html links to ${m[3]}`);
    else assert.match(m[3], /^(data:,|[a-z][\w./-]*)$/, `index.html loads ${m[3]}`);
  }
  for (const m of HTML.matchAll(/<a\b[^>]*>/g)) assert.match(m[0], /rel="noopener"/, 'site links open with rel=noopener');
});

test('no innerHTML / eval / new Function / string timers / document.write anywhere', () => {
  for (const f of JS.concat(pub('index.html'))) {
    // brand/*.js say in their header comments that they avoid these APIs; there only the code counts
    const s = rel(f).startsWith('brand/') ? read(f).replace(/\/\*[\s\S]*?\*\//g, '') : read(f);
    for (const bad of [/\binnerHTML\b/, /\bouterHTML\b/, /insertAdjacentHTML/, /\beval\s*\(/, /new\s+Function\b/, /document\.write/, /setTimeout\(\s*['"`]/, /setInterval\(\s*['"`]/]) {
      assert.doesNotMatch(s, bad, `${rel(f)} uses ${bad}`);
    }
  }
});

test('index.html: CSP-compatible (no inline script/style, no on*=), noindex, zh-CN, ids the e2e test drives', () => {
  assert.doesNotMatch(HTML, /<script(?![^>]*\ssrc=)[^>]*>/i);
  assert.doesNotMatch(HTML, /<style[\s>]/i);
  assert.doesNotMatch(HTML, /<[a-z][^>]*\s(style|on[a-z]+)\s*=/i);
  assert.match(HTML, /<meta name="robots" content="noindex,nofollow">/);
  assert.match(HTML, /<html lang="zh-CN">/);
  assert.match(HTML, /data-i18n="badge.label"[^>]*>网页版</);
  assert.match(HTML, /<script src="brand\/lang\.js"><\/script>/, 'lang.js runs synchronously in <head> (sets <html lang> before paint)');
  assert.match(HTML, /原生 App（计划中/);                       // A2 review M-4: nothing promised in the present tense
  assert.doesNotMatch(HTML, /在公开源码上运行[^<]*结果应与上面一致/);   // the source is not public yet
  assert.match(APP, /parseLink\(input, undefined, allowRelay\)/); // A2 review L-2: the relay is pinned
  for (const id of ['status', 'pair-link', 'pair-go', 'scan', 'sas', 'messages', 'msg-input', 'send', 'badge', 'badge-panel', 'version-hash', 'repair', 'retry']) {
    assert.match(HTML, new RegExp(`id="${id}"`), `missing #${id}`);
  }
});

test('app.js: only WebSocket egress, non-extractable device key, no plaintext at rest, no logging', () => {
  for (const bad of [/\bfetch\s*\(/, /XMLHttpRequest/, /sendBeacon/, /\bEventSource\b/, /sessionStorage/, /\bconsole\./, /exportKey/, /document\.cookie/, /postMessage/]) {
    assert.doesNotMatch(APP, bad, `app.js uses ${bad}`);
  }
  // localStorage: only the "Add to Home Screen hint dismissed" flag (brand/lang.js keeps the language + theme); never chat text
  assert.deepEqual([...APP.matchAll(/localStorage\.(\w+)\(([^,)]*)/g)].map((m) => `${m[1]}(${m[2]})`).sort(), ['getItem(A2HS_KEY)', 'setItem(A2HS_KEY)']);
  assert.match(APP, /const A2HS_KEY = 'aj\.a2hs';/);
  assert.equal((APP.match(/localStorage/g) || []).length, 2, 'localStorage appears only in the two A2HS lines');
  assert.match(APP, /generateKeypair\(false\)/);
  assert.match(APP, /history\.replaceState/);
  assert.match(APP, /textContent = text/);
  assert.deepEqual([...APP.matchAll(/dbPut\('(\w+)'/g)].map((m) => m[1]).sort(), ['device', 'host', 'sign'], 'IndexedDB writes: device key + approval key + host record only');
  assert.match(APP, /generateSigningKeypair\(\)/);
  const WIRE = readFileSync(new URL('../../protocol/wire.js', import.meta.url), 'utf8');
  assert.match(WIRE, /generateKey\(\{ name: 'Ed25519' \}, false, \['sign', 'verify'\]\)/, 'approval key: private half not extractable');
  assert.match(APP, /from '\.\/proto\/noise\.js'/);
  assert.match(APP, /from '\.\/proto\/wire\.js'/);
});

// ---------------------------------------------------------------- Worker
const RELAY = 'wss://alpha-relay.agentjarvis.net';
const env = () => ({ WEB_HOST: 'alpha-web.agentjarvis.net', RELAY_URL: RELAY,
  ASSETS: { fetch: async (req) => new Response(req.method === 'HEAD' ? null : '<html>client</html>', { headers: { 'content-type': 'text/html' } }) } });
const req = (url, { method = 'GET', headers = {} } = {}) => new Request(url, { method, headers });

test('worker: public (no Access since 2026-10-02) → asset with the full header set, still noindex', async () => {
  const r = await handle(req('https://alpha-web.agentjarvis.net/'), env());
  assert.equal(r.status, 200);
  assert.equal(await r.text(), '<html>client</html>');
  assert.equal(r.headers.get('content-security-policy'),
    "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data: blob:; connect-src wss://alpha-relay.agentjarvis.net; " +
    "media-src 'self' blob:; frame-ancestors 'none'; base-uri 'none'; form-action 'none'; object-src 'none'");
  assert.equal(r.headers.get('permissions-policy'), 'camera=(self), microphone=(), geolocation=()');
  assert.equal(r.headers.get('x-robots-tag'), 'noindex, nofollow, noarchive');
  assert.equal(r.headers.get('referrer-policy'), 'no-referrer');
  assert.equal(r.headers.get('x-frame-options'), 'DENY');
  assert.equal(r.headers.get('x-content-type-options'), 'nosniff');
  assert.match(r.headers.get('strict-transport-security'), /max-age=\d+/);
  assert.equal(r.headers.get('cache-control'), 'private, no-store');
  assert.equal((await handle(req('https://alpha-web.agentjarvis.net/app.js', { method: 'HEAD' }), env())).status, 200);
  // a stale / forged Access header changes nothing
  assert.equal((await handle(req('https://alpha-web.agentjarvis.net/', { headers: { 'cf-access-jwt-assertion': 'a.b.c' } }), env())).status, 200);
});

test('worker: wrong host, non-GET/HEAD, malformed RELAY_URL → bare 404 without the asset', async () => {
  const cases = [
    req('https://alpha.agentjarvis.net/'),
    req('https://agentjarvis-web.example.workers.dev/'),
    req('https://web.agentjarvis.net/'),
    req('https://alpha-web.agentjarvis.net/', { method: 'POST' }),
    req('https://alpha-web.agentjarvis.net/', { method: 'PUT' }),
    req('https://alpha-web.agentjarvis.net/', { method: 'DELETE' }),
  ];
  for (const r of cases) {
    const res = await handle(r, env());
    assert.equal(res.status, 404, `${r.method} ${r.url}`);
    assert.equal(await res.text(), 'Not Found');
  }
  for (const RELAY_URL of ["wss://x; script-src 'unsafe-inline'", 'ws://alpha-relay.agentjarvis.net', '']) {
    assert.equal((await handle(req('https://alpha-web.agentjarvis.net/'), { ...env(), RELAY_URL })).status, 404, `malformed RELAY_URL ${RELAY_URL} fails closed`);
  }
});

test('worker: self-contained (no imports, so it builds from the public tree); csp()/webHeaders() are what serve.mjs reuses; wrangler.toml pins the brief', () => {
  const W = read(join(PUBLIC_DIR, '..', 'worker.ts'));
  assert.doesNotMatch(W, /^\s*import\b/m, 'worker.ts must not import anything');
  assert.doesNotMatch(W, /cf-access|Access JWT|verifyAccess/i, 'no Access check left');
  assert.match(csp('ws://127.0.0.1:*'), /connect-src ws:\/\/127\.0\.0\.1:\*;/);
  assert.equal(Object.keys(webHeaders(RELAY)).length, 8);
  const t = read(join(PUBLIC_DIR, '..', 'wrangler.toml'));
  for (const line of ['name = "agentjarvis-web"', 'main = "worker.ts"', 'compatibility_date = "2026-09-01"',
    'workers_dev = false', 'preview_urls = false', 'pattern = "alpha-web.agentjarvis.net", custom_domain = true', 'directory = "public"', 'binding = "ASSETS"',
    'run_worker_first = true', 'WEB_HOST = "alpha-web.agentjarvis.net"', 'RELAY_URL = "wss://alpha-relay.agentjarvis.net"']) {
    assert.ok(t.includes(line), `wrangler.toml missing: ${line}`);
  }
  assert.match(t, /\[observability\]\nenabled = false/);
  assert.doesNotMatch(t, /ACCESS_/, 'no Access vars');
  const acct = t.match(/^account_id = "(.*)"$/m);
  if (acct) assert.match(acct[1], /^[0-9a-f]{32}$/);   // the public copy has no account_id (set your own)
});

// ---------------------------------------------------------------- L1: service worker + manifest (PROTOCOL §9)
test('sw.js: push display only — no fetch handler, no cache, no network, generic text only', () => {
  const SW = readFileSync(join(PUBLIC_DIR, 'sw.js'), 'utf8');
  for (const bad of [/addEventListener\(\s*['"]fetch/, /\bcaches\b/, /\bfetch\s*\(/, /importScripts/, /XMLHttpRequest/, /\bconsole\./, /indexedDB/]) {
    assert.doesNotMatch(SW, bad, `sw.js uses ${bad}`);
  }
  assert.match(SW, /zh: \{ reply: '有新回复', ask: '有一个请求等你批准' \}/);
  assert.match(SW, /en: \{ reply: 'New reply', ask: 'A request is waiting for your approval' \}/);
  assert.match(SW, /showNotification\('Agent Jarvis', \{ body: BODY\[LANG\]\[k\]/, 'the notification body is one of the two fixed sentences');
  assert.match(SW, /const SW_VERSION = 'aj-web-[\w-]+';/, 'sw.js carries a version string (bumped with each shell redesign)');
  const APP2 = readFileSync(join(PUBLIC_DIR, 'app.js'), 'utf8');
  assert.match(APP2, /userVisibleOnly: true/);
  assert.match(APP2, /serviceWorker\.register\('sw\.js'/);
});

test('manifest + icons are local files from the brand (192, 512, 512 maskable), colours from tokens', () => {
  const m = JSON.parse(readFileSync(join(PUBLIC_DIR, 'manifest.webmanifest'), 'utf8'));
  assert.equal(m.display, 'standalone');
  assert.equal(m.name, 'Agent Jarvis');
  assert.ok(m.short_name && m.short_name.length <= 12);
  for (const i of m.icons) assert.ok(!/^[a-z]+:/i.test(i.src) && i.src.startsWith('brand/img/') && statSync(join(PUBLIC_DIR, i.src)).size > 0, i.src);
  assert.deepEqual(m.icons.map((i) => `${i.sizes}/${i.purpose}`), ['192x192/any', '512x512/any', '512x512/maskable']);
  const TOK = read(pub('brand/palette.css'));
  for (const c of [m.background_color, m.theme_color]) assert.ok(TOK.includes(`: ${c};`), `${c} is a brand token`);
  assert.match(HTML, /<meta name="theme-color" content="#faf9f5" media="\(prefers-color-scheme: light\)">/);
  assert.match(HTML, /<meta name="theme-color" content="#141414" media="\(prefers-color-scheme: dark\)">/);
  assert.match(HTML, /<link rel="apple-touch-icon" href="apple-touch-icon\.png">/);
  assert.match(HTML, /<link rel="manifest" href="manifest\.webmanifest">/);
});

// ---------------------------------------------------------------- brand + i18n
test('brand copy is current (brand/sync.mjs --set web --check)', { skip: !HAVE_BRAND && 'no agentjarvis/brand (public export)' }, () => {
  const r = spawnSync(process.execPath, [fileURLToPath(new URL('../../brand/sync.mjs', import.meta.url)), PUBLIC_DIR, '--set', 'web', '--check'], { encoding: 'utf8' });
  assert.equal(r.status, 0, r.stdout + r.stderr);
});

const DICT = dictionaries();
const ph = (s) => (s.match(/\{\w+\}/g) || []).sort().join(' ');
test('i18n: zh and en have the same keys and placeholders; i18n.js and index.html are built from them', () => {
  assert.deepEqual(Object.keys(DICT.en).sort(), Object.keys(DICT.zh).sort());
  for (const k of Object.keys(DICT.zh)) {
    assert.equal(ph(DICT.en[k]), ph(DICT.zh[k]), `placeholders differ for ${k}`);
    assert.ok(DICT.zh[k].trim() && DICT.en[k].trim(), `empty string for ${k}`);
    assert.equal((DICT.zh[k].match(/`/g) || []).length % 2, 0, `unbalanced backticks zh ${k}`);
    assert.equal((DICT.en[k].match(/`/g) || []).length % 2, 0, `unbalanced backticks en ${k}`);
  }
  assert.equal(read(pub('i18n.js')), i18nModule(DICT), 'public/i18n.js is stale — run build.mjs');
  assert.equal(HTML, syncHtml(HTML, DICT.zh), 'index.html Chinese text differs from web.zh.json — run build.mjs');
  for (const m of HTML.matchAll(/data-i18n="([\w.]+)"/g)) assert.ok(DICT.zh[m[1]], `index.html: unknown key ${m[1]}`);
  for (const m of APP.matchAll(/\bt\('([\w.]+)'/g)) {
    if (m[1].endsWith('.')) assert.ok(Object.keys(DICT.zh).some((k) => k.startsWith(m[1])), `app.js: no keys under ${m[1]}`);
    else assert.ok(DICT.zh[m[1]], `app.js: unknown key ${m[1]}`);
  }
});

test('i18n: the Chinese is the polished output (i18n/polish.py --check, offline)', { skip: !existsSync(POLISH) && 'no agentjarvis/i18n (public export)' }, () => {
  const r = spawnSync('python3', [POLISH, '--check', I18N_DIR], { encoding: 'utf8' });
  assert.equal(r.status, 0, r.stdout + r.stderr);
});

// glossary.json "forbidden" patterns are Python regexes: a leading (?i) becomes the JS i flag; (?i:…) groups are native
const GLOSSARY = existsSync(GLOSSARY_FILE) ? JSON.parse(read(GLOSSARY_FILE)) : null;
const NO_GLOSSARY = !GLOSSARY && 'no agentjarvis/i18n (public export)';
const jsRe = (p) => (p.startsWith('(?i)') ? new RegExp(p.slice(4), 'i') : new RegExp(p));
test('i18n: no internal terms or banned words in either dictionary, the page text or app.js literals', { skip: NO_GLOSSARY }, () => {
  const visible = HTML.replace(/<script[\s\S]*?<\/script>|<[^>]+>/g, ' ');
  const sources = [...Object.entries(DICT.zh).map(([k, v]) => [`zh ${k}`, v]), ...Object.entries(DICT.en).map(([k, v]) => [`en ${k}`, v]), ['index.html text', visible]];
  for (const f of GLOSSARY.forbidden) {
    const re = jsRe(f.pattern);
    for (const [where, text] of sources) assert.doesNotMatch(text, re, `${where}: internal term /${f.pattern}/ — say 「${f.say_zh}」 / "${f.say_en}"`);
  }
  for (const [k, v] of Object.entries(DICT.zh)) {
    for (const w of GLOSSARY.banned_words_zh) assert.ok(!v.includes(w), `zh ${k}: banned word ${w}`);
    for (const p of GLOSSARY.banned_patterns_zh) assert.doesNotMatch(v, new RegExp(p), `zh ${k}: banned pattern ${p}`);
  }
  // every user-visible Chinese string lives in the dictionary: app.js code has no Chinese except the device label sent to
  // the host ("网页 · Chrome" is data for the computer's device list) and comments
  const code = APP.replace(/\/\/.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '');
  const cjk = [...new Set(code.match(/[㐀-鿿]+/g) || [])];
  assert.ok(cjk.includes('网页') && cjk.every((w) => ['浏览器', '网页'].includes(w)), `app.js has UI Chinese outside the dictionary: ${cjk.join(' ')}`);
});

test('i18n: the forbidden-term check itself works (positive control)', { skip: NO_GLOSSARY }, () => {
  const planted = ['Noise 握手', '急停', 'alpha', 'harness', 'Zero Access'];
  for (const s of planted) assert.ok(GLOSSARY.forbidden.some((f) => jsRe(f.pattern).test(s)), `no forbidden pattern catches ${s}`);
});

