#!/usr/bin/env node
// agentjarvis web client — build step (zero npm deps, deterministic, no timestamps).
//   1. copies protocol/{noise,wire}.js → public/proto/ byte-for-byte (the client must not carry its own crypto)
//   2. writes public/version.json (+ public/version.js, the same manifest as an ES module: CSP connect-src only allows the
//      relay, so the page cannot fetch() version.json — it imports version.js instead)
// Manifest = SHA-256 of every shipped file except the two manifest files themselves (they are deterministic outputs of
// this script), plus `combined` = SHA-256 of the sha256sum-style listing "<hex>  <path>\n" sorted by path.
//
//   node web/build.mjs                build
//   node web/build.mjs --print-hash   print the combined hash computed from the SOURCE (writes nothing)
import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { join, relative, sep } from 'node:path';

export const WEB_DIR = fileURLToPath(new URL('./', import.meta.url));
export const PUBLIC_DIR = join(WEB_DIR, 'public');
export const PROTOCOL_DIR = fileURLToPath(new URL('../protocol/', import.meta.url));
export const PROTO_FILES = ['noise.js', 'wire.js'];
export const MANIFEST_FILES = new Set(['version.json', 'version.js']);

const sha = (buf) => createHash('sha256').update(buf).digest('hex');
const walk = (d) => readdirSync(d).flatMap((n) => { const p = join(d, n); return statSync(p).isDirectory() ? walk(p) : [p]; });
const relPosix = (p) => relative(PUBLIC_DIR, p).split(sep).join('/');

/** { path → Buffer } of everything that ships, with proto/* taken from protocol/ (the source of truth). */
export function sourceFiles() {
  const out = new Map();
  for (const f of walk(PUBLIC_DIR)) {
    const r = relPosix(f);
    if (MANIFEST_FILES.has(r) || r.startsWith('proto/')) continue;
    out.set(r, readFileSync(f));
  }
  for (const n of PROTO_FILES) out.set(`proto/${n}`, readFileSync(join(PROTOCOL_DIR, n)));
  return out;
}

export function manifest(files) {
  const paths = [...files.keys()].sort();
  const entries = Object.fromEntries(paths.map((p) => [p, sha(files.get(p))]));
  const listing = paths.map((p) => `${entries[p]}  ${p}\n`).join('');
  return { v: 1, algo: 'sha256', combined: sha(listing), files: entries };
}

export function build() {
  const files = sourceFiles();
  mkdirSync(join(PUBLIC_DIR, 'proto'), { recursive: true });
  for (const n of PROTO_FILES) writeFileSync(join(PUBLIC_DIR, 'proto', n), files.get(`proto/${n}`));
  const m = manifest(files);
  const json = JSON.stringify(m, null, 2) + '\n';
  writeFileSync(join(PUBLIC_DIR, 'version.json'), json);
  writeFileSync(join(PUBLIC_DIR, 'version.js'), `// generated by build.mjs — do not edit\nexport default ${json.trimEnd()};\n`);
  return m;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  if (process.argv.includes('--print-hash')) {
    console.log(manifest(sourceFiles()).combined);
  } else {
    const m = build();
    for (const [p, h] of Object.entries(m.files)) console.log(`${h}  ${p}`);
    console.log(`combined ${m.combined}`);
  }
}
