#!/usr/bin/env node
// agentj web client — build step (zero npm deps, deterministic, no timestamps).
//   1. copies protocol/{noise,wire}.js → public/proto/ byte-for-byte (the client must not carry its own crypto)
//   2. (in the monorepo) copies the shared design system (agentjarvis/brand, set "web": tokens, base, lang.js, ui.js, fonts, shield + PWA +
//      status icons) → public/brand/… + public/favicon.ico + public/apple-touch-icon.png (same as `brand/sync.mjs --set web`)
//   3. writes public/i18n.js from web/i18n/web.zh.json (polished by i18n/polish.py) + web/i18n/web.en.json — an ES module,
//      because customer data uses only the relay; P120 permits a fixed metadata-only version.json GET
//   4. rewrites the Chinese text inside every [data-i18n] / [data-i18n-attr] element of public/index.html from web.zh.json
//      (the no-JS default stays identical to the dictionary)
//   5. writes public/version.json (+ public/version.js, the same manifest as an ES module)
// Manifest = SHA-256 of every shipped file except the two manifest files themselves (they are deterministic outputs of
// this script), plus `combined` = SHA-256 of the sha256sum-style listing "<hex>  <path>\n" sorted by path. Every generated
// or copied file is computed from its SOURCE (protocol/, brand/, web/i18n/), so --print-hash never trusts public/ copies.
//
//   node web/build.mjs                build
//   node web/build.mjs --print-hash   print the combined hash computed from the SOURCE (writes nothing)
import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { join, relative, sep, dirname } from 'node:path';

// The design system lives in agentjarvis/brand/. The public source export ships web/ alone: there the committed
// public/brand/ copy is the source (same bytes), so the build and --print-hash work in both trees.
export const BRAND_DIR = fileURLToPath(new URL('../brand/', import.meta.url));
export const HAVE_BRAND = existsSync(join(BRAND_DIR, 'sync.mjs'));
const brandPlan = HAVE_BRAND ? (await import('../brand/sync.mjs')).plan : null;

export const WEB_DIR = fileURLToPath(new URL('./', import.meta.url));
export const PUBLIC_DIR = join(WEB_DIR, 'public');
export const I18N_DIR = join(WEB_DIR, 'i18n');
export const PROTOCOL_DIR = fileURLToPath(new URL('../protocol/', import.meta.url));
export const PROTO_FILES = ['noise.js', 'wire.js'];
export const MANIFEST_FILES = new Set(['version.json', 'version.js']);
export const LANGS = ['zh', 'en'];

const sha = (buf) => createHash('sha256').update(buf).digest('hex');
const walk = (d) => readdirSync(d).flatMap((n) => { const p = join(d, n); return statSync(p).isDirectory() ? walk(p) : [p]; });
const relPosix = (p) => relative(PUBLIC_DIR, p).split(sep).join('/');

/** { "a.b": "text" } from nested JSON. */
export function flatten(obj, prefix = '', out = {}) {
  for (const [k, v] of Object.entries(obj)) {
    const key = prefix ? `${prefix}.${k}` : k;
    if (v && typeof v === 'object') flatten(v, key, out); else if (typeof v === 'string') out[key] = v;
  }
  return out;
}
export function dictionaries() {
  return Object.fromEntries(LANGS.map((l) => [l, flatten(JSON.parse(readFileSync(join(I18N_DIR, `web.${l}.json`), 'utf8')))]));
}
export function i18nModule(d = dictionaries()) {
  return `// generated by build.mjs from web/i18n/web.{zh,en}.json — do not edit\nexport default ${JSON.stringify(d, null, 1)};\n`;
}

const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const escAttr = (s) => esc(s).replace(/"/g, '&quot;');
const noTicks = (s) => s.replace(/`/g, '');
/** index.html with every data-i18n text / data-i18n-attr attribute set to the Chinese dictionary value. */
export function syncHtml(html, zh = dictionaries().zh) {
  const miss = (k) => { throw new Error(`index.html uses unknown i18n key ${k}`); };
  html = html.replace(/(<(\w+)\b[^>]*\sdata-i18n="([\w.]+)"[^>]*>)([^<]*)(<\/\2>)/g,
    (m, open, tag, key, _text, close) => open + esc(noTicks(zh[key] ?? miss(key))) + close);
  html = html.replace(/<[a-z]+\b[^>]*\sdata-i18n-attr="([^"]+)"[^>]*>/g, (tagText, spec) => {
    for (const pair of spec.split(',')) {
      const [a, k] = pair.split('=').map((x) => x.trim());
      const v = escAttr(noTicks(zh[k] ?? miss(k)));
      const re = new RegExp(`(\\s${a}=")[^"]*(")`);
      tagText = re.test(tagText) ? tagText.replace(re, `$1${v}$2`) : tagText.replace(/>$/, ` ${a}="${v}">`);
    }
    return tagText;
  });
  return html;
}

/** { path → Buffer } of everything that ships, with the copied / generated files taken from their sources. */
export function sourceFiles() {
  const out = new Map();
  for (const f of walk(PUBLIC_DIR)) {
    const r = relPosix(f);
    if (MANIFEST_FILES.has(r) || r.startsWith('proto/') || (HAVE_BRAND && r.startsWith('brand/'))) continue;
    out.set(r, readFileSync(f));
  }
  for (const n of PROTO_FILES) out.set(`proto/${n}`, readFileSync(join(PROTOCOL_DIR, n)));
  if (HAVE_BRAND) for (const { src, dst } of brandPlan(PUBLIC_DIR, 'web')) out.set(relPosix(dst), readFileSync(src));
  const d = dictionaries();
  out.set('i18n.js', Buffer.from(i18nModule(d)));
  out.set('index.html', Buffer.from(syncHtml(readFileSync(join(PUBLIC_DIR, 'index.html'), 'utf8'), d.zh)));
  return out;
}

export function manifest(files) {
  const paths = [...files.keys()].sort();
  const entries = Object.fromEntries(paths.map((p) => [p, sha(files.get(p))]));
  const listing = paths.map((p) => `${entries[p]}  ${p}\n`).join('');
  const version = readFileSync(new URL('../host/agentj/__init__.py', import.meta.url), 'utf8').match(/^__version__ = "([^"]+)"$/m)?.[1];
  if (!version) throw new Error('host release version missing');
  return { v: 1, version, algo: 'sha256', combined: sha(listing), files: entries };
}

export function build() {
  const files = sourceFiles();
  for (const [r, buf] of files) {
    const dst = join(PUBLIC_DIR, ...r.split('/'));
    mkdirSync(dirname(dst), { recursive: true });
    let same = false;
    try { same = readFileSync(dst).equals(buf); } catch { /* new file */ }
    if (!same) writeFileSync(dst, buf);
  }
  const m = manifest(files);
  const json = JSON.stringify(m, null, 2) + '\n';
  writeFileSync(join(PUBLIC_DIR, 'version.json'), json);
  writeFileSync(join(PUBLIC_DIR, 'version.js'), `// generated by build.mjs — do not edit\nexport default ${json.trimEnd()};\n`);
  return m;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  if (process.argv.includes('--print-hash')) {
    console.log(manifest(sourceFiles()).combined);
  } else {
    const m = build();
    for (const [p, h] of Object.entries(m.files)) console.log(`${h}  ${p}`);
    console.log(`combined ${m.combined}`);
  }
}
